# Paths
paths:
  data_dir: /projects/OVTMA_project/data/OVTMA_fov216
  cell_rds: cell_level_216fov_forCaitlin_withHLAI.rds         # .rds with cell-level x,y, phenotype, ROI
  roi_labels_csv: fov_level_216fov_forCaitlin.csv       # CSV with ROI→patient mapping
  subject_labels_csv: subject_level_216fov_forCaitlin.csv # CSV with patient-level features

# Column names in the cell .rds
cell_columns:
  x: x
  y: y
  phenotype: metacluster
  cell_id: tumor_cell_index
  roi_id: FOV

# Column names in the ROI-level label file
roi_label_columns:
  roi_id: FOV
  patient_id: Participant

# Column names in the subject-level label file
subject_label_columns:
  patient_id: Participant
  # any additional subject-level features will be merged as-is

# Graph options (choose at runtime too)
graph:
  type: gabriel        # one of: knn, radius, gabriel
  knn_k: 8
  radius: 25.0

# Embedding hooks (resolved at runtime)
embeddings:
  structure:
    method: fastrp
    params:
      dim: 64
      weights: [1.0, 0.5, 0.25, 0.125]
      projection_method: sparse # gaussian/sparse , sparse in the paper
      input_matrix: trans # adj/trans, trans in the paper
      normalization: False
      alpha: 
      weight: 
      #C: 1.0
    order_range: 2
    aux_column: phenotype
  node_attributes:
    method: passthrough    # e.g., use raw marker/phenotype encodings

# Fusion / Aggregation / Auxiliary loss — names map to stub registry in code
fusion:
  method: concat

aggregation:
  method: mean_pool        # choices: mean_pool, attention_stub

auxiliary_loss:
  method: none
  params: {}
