# Paths
paths:
  data_dir: /projects/wangc/m344313/OVTMA_project/data/OVTMA_fov297
  cell_rds: combined.rds         # .rds with cell-level x,y, phenotype, ROI
  roi_labels_csv: OVTMA22_metadata.csv       # CSV with ROI→patient mapping OR ROI lables if on subject level
  subject_labels_csv: 

# Column names in the cell .rds
cell_columns:
  x: x
  y: y
  phenotype: metacluster
  cell_id: cell_id
  roi_id: region

# Column names in the ROI-level label file
roi_label_columns:
  roi_id: FOV
  roi_label: histology

# Graph options (choose at runtime too)
graph:
  type: gabriel        # one of: knn, radius, gabriel
  knn_k: 8
  radius: 25.0


auxiliary_loss:
  method: none
  params: {}

roi_supervision:
  enabled: true
  group_col:          # optional; groups CV by subject/patient if available
  n_splits: 5
  random_state: 42
  n_jobs: 10

  # Fixed knobs (stay constant across trials)
  params_fixed:
    structure_method: fastrp-het
    fusion_mode: none # fastrp-het only supports none
    attr_method: passthrough
    attr_cols: #additional columns to concatenate(ex. functional markers)
    normalization: False
    projection_method: sparse # gaussian/sparse , sparse in the paper
    input_matrix: trans # adj/trans, trans in the paper
    weights: 

  params_search_space:
    l1_ratio: [0.0, 0.25,0.5,0.75, 1.0]
    dim: [64, 128, 256,512]
    
    aggregation_choices: ['mean_pool', 'add_pool','sum_pool', 'max_pool',
                        'set2set', 'global_attention',
                        'softmax_pool', 'powermean_pool', 'lstm_pool',
                        'mil_mean', 'mil_max', 'mil_attention']