# Paths
paths:
  data_dir: /projects/wangc/m344313/OVTMA_project/data/OVTMA_fov216
  cell_rds: combined.rds         # .rds with cell-level x,y, phenotype, ROI
  roi_labels_csv: fov_level_216fov_forCaitlin.csv     # CSV with ROI→patient mapping OR ROI lables if on subject level
  subject_labels_csv: subject_level_216fov_forCaitlin.csv

# Column names in the cell .rds
cell_columns:
  x: x
  y: y
  phenotype: metacluster
  cell_id: cell_id
  roi_id: region

# Column names in the ROI-level label file
roi_label_columns:
  roi_id: FOV
  roi_label: histology
  patient_id: Participant

# Column names in the subject-level label file
subject_label_columns:
  patient_id: Participant
  patient_label: histology

# Graph options (choose at runtime too)
graph:
  type: gabriel        # one of: knn, radius, gabriel
  knn_k: 8
  radius: 25.0


auxiliary_loss:
  method: none
  params: {}

roi_supervision:
  enabled: true
  group_col:          # optional; groups CV by subject/patient if available
  n_splits: 5
  random_state: 42
  n_jobs: 10
  score_types: ["accuracy", "average_acc", "roc_auc"]
  # Fixed knobs (stay constant across trials)
  params_fixed:
    structure_method: fastrp
    attr_method: passthrough
    attr_cols: #additional columns to concatenate(ex. functional markers)
    normalization: False
    projection_method: sparse # gaussian/sparse , sparse in the paper
    input_matrix: trans # adj/trans, trans in the paper
    weights:
  # Search space (randomly sampled)
  params_search_space:
    l1_ratio: [0.0, 0.25,0.5,0.75, 1.0]
    fusion_mode: ["none", "concat"] 
    dim: [64, 128, 256,512]
    aggr_method: ['mean_pool', 'add_pool', 'max_pool',
                       'set2set', 'global_attention',
                       'softmax_pool', 'powermean_pool', 'lstm_pool',
                       'mil_mean', 'mil_max', 'mil_attention']
